#This is a generated file.
# The values in this file have syntax:   key = value
#User modifications to the values in this file will be preserved
#Wed Sep 17 19:16:58 CEST 2025
CronTriggerInput=CronTriggerInput
Property.timeZone=Scheduled timeZone
Property.cron=cron
Group.Cron=Cron
OutTerminal.catch=catch
OutTerminal.failure=failure
OutTerminal.out=out
