#
#Wed Sep 17 18:40:52 CEST 2025
bin.includes=META-INF/,**/*.msgnode,**/*.templatemsgnode,**/*.msgflow,**/*.properties,**/*.custom,**/*.esql,**/*.map,**/*.msgmap,HelpContexts.xml,palette.xmi,plugin.xml,icons/,.,generated/
source..=src/
output..=bin/
