#This is a generated file.
# The values in this file have syntax:   key = value
#User modifications to the values in this file will be preserved
#Thu Sep 18 08:11:31 CEST 2025
entry.com.ace.cron.CronTriggerInput=CrontTriggerInput
category.name=Timer
tooltip.com.ace.cron.CronTriggerInput=CrontTriggerInput
